### ISSUE TITLE
Pick logo

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#14]
A logo is good to have, an icon to have in your browser history / URL bar / tabs / favorites.

I really like this website for icons: https://thenounproject.com/

Haven't been able to find anything yet that I feel describes the project well.

**Comment by mbernste** [comment]
Here are a few that caught my eye:

https://thenounproject.com/search/?q=sequence&i=383356
https://thenounproject.com/search/?q=Metadata&i=38248
https://thenounproject.com/search/?q=sequence&i=383342
https://thenounproject.com/search/?q=data&i=787659

**Comment by mziegler** [comment]
Out of those, I like that first one the best.  It doesn't do much to describe what the website is for, but it is eye-catching.  

I've been really struggling to find / design an icon that is descriptive though (other than a boring, generic DNA helix) so maybe we shouldn't set our hopes too high for descriptiveness.

**Comment by mbernste** [comment]
I like the first one also. I think it sort of conveys the website.  The layers convey the idea of "meta" or "above" in that the MetaSRA sits above the SRA as a layer.  I would avoid a DNA helix, it's pretty generic.

**Comment by mbernste** [comment]
Here are a few more that convey "layers" as in "meta" in metadata: 
https://thenounproject.com/search/?q=layer&i=1241790
https://thenounproject.com/search/?q=layer&i=1276247
https://thenounproject.com/search/?q=layer&i=1241827

Maybe a compass would be a good logo, since this project is all about "navigating" messy datasets:
https://thenounproject.com/search/?q=compass&i=1265339
https://thenounproject.com/search/?q=compass&i=844727
https://thenounproject.com/search/?q=compass&i=1122571

**Comment by mziegler** [comment]
Going with this one for now:
https://thenounproject.com/search/?q=layer&i=1132013

A variant of one you suggested, that minimizes better to 16x16 for the status bar icon
