### ISSUE TITLE
Too much space between top of website and interface

### ISSUE THREAD

**Issue by mbernste** [deweylab/MetaSRA-website-frontend#23]
I think there's too much space between the top of the page and the web interface. Perhaps the title should go above the links to the supporting pages (similar to how it is laid out in the current version of the website):
![space](https://user-images.githubusercontent.com/5004419/31317987-402586c8-ac10-11e7-942f-4706baaefc5a.png)

**Comment by mziegler** [comment]
I'm reluctant to reduce the amount of space here, because I think it's important for enforcing the visual hierarchy, and for creating separation between the different parts of the page.  For the very first impression, we want the user's eyeballs to first notice "MetaSRA," then "Find human sequence-read samples", and then the search-box.  

The white space adds emphasis to the logo and the top of the search box - I think moving the links down would add too much noise.  The navigation links shouldn't be be as noticeable, and users are used to looking for them at the top of the page if they want more information.  This is a common design convention - see the front page of http://google.com ,  and https://getbootstrap.com/ .

Designers-always-want-more-whitespace / programmers-wanting-less-whitespace is a long-running trope.  Here's an article I like about whitespace.  https://medium.com/wayfair-design/more-padding-please-b95e19422acc
"Think you’re using too much white space? There’s a good chance you’re not. If anything, you’re probably not using enough. When in doubt, add more white space."

I haven't done much first-impression-testing yet, (showing the page to people in the target audience who have never heard of this project, and seeing if they can quickly figure out what the website is for and what they should do with it.)  I think that will give us good feedback about this question.

**Comment by mbernste** [comment]
Hmm, maybe so. I could probably be convinced. If we stick with this, then I think the logos in the upper right corner should be moved to the bottom. Visually, they take up the attention when I first look at the page.

As another argument against some of this whitespace, on my laptop, the examples at the bottom are obscured/cut off.  Maybe the white space should be reduced somewhat in order to fit the examples?
